### ISSUE TITLE
Investigar como se aplican los rangos de costos que aplican para las multas

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [codice-progressio/veritas-totus-tui-sui#5]
*Revisar descripción de epic para ver la normativa actual que estamos consultando. 

- [ ] ¿Cuánto debe cobrar caja ?
- [ ] ¿Quién define el valor final de la multa?

# OPCION DE RESOLUCIÓN

> Permitir que un administrativo modifica el precio de la multa o aplique descuento y cancele ( con justificación ). Reporte de actividades de actividades de cobro (contabilidad en multas)

**Comment by jonadlc** [comment]
siempre se cobra el mínimo de las estimaciones (Depende mucho la visión de cada gobierno)  y el valor lo anexa quien en la etapa administrativa sube la base datos al sistema local ya con la tabulación mínima.
